// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG-cNs02_qwA07sZgEKfAwlFAgSEIo6A0',
    appId: '1:576261762950:android:82cb1b0ba916f9de7e4607',
    messagingSenderId: '576261762950',
    projectId: 'kingoflotto-ee288',
    storageBucket: 'kingoflotto-ee288.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd8f4qGMCj-v0uQbZbIgd3nF1ctBB9UBs',
    appId: '1:576261762950:ios:e6c4aedf61c29de97e4607',
    messagingSenderId: '576261762950',
    projectId: 'kingoflotto-ee288',
    storageBucket: 'kingoflotto-ee288.appspot.com',
    // ios 패키지네임이며, Xcode에서 변경가능
    iosBundleId: 'com.example.kingoflotto',
  );
}
